### ISSUE TITLE
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

### ISSUE THREAD

**Issue by hexray-newbee** [GB28181/GB28181.Solution#12]
```sh
docker build -t gbs .
docker run gbs
```

```
2020-06-01 05:06:31.115 [Debug]: Target framework: .Net Core 3.1
2020-06-01 05:06:31.137 [Debug]: EnvironmentVariables.MICRO_REGISTRY_ADDRESS:
2020-06-01 05:06:31.137 [Debug]: EnvironmentVariables.GB_NATS_CHANNEL_ADDRESS:
2020-06-01 05:06:31.137 [Debug]: EnvironmentVariables.DEVICE_MANAGEMENT_SERVICE_ADDRESS:
2020-06-01 05:06:31.138 [Debug]: EnvironmentVariables.SYSTEM_CONFIGURATION_SERVICE_ADDRESS:
2020-06-01 05:06:31.138 [Debug]: EnvironmentVariables.GB_SERVICE_LOCAL_IP:
2020-06-01 05:06:31.138 [Debug]: EnvironmentVariables.GB_SERVICE_LOCAL_ID:
2020-06-01 05:06:31.138 [Debug]: EnvironmentVariables.GBServerGrpcPort: 50051
2020-06-01 05:06:31.138 [Debug]: Notes: if EnvironmentVariables have no value, it gets from xml config.
2020-06-01 05:06:31.323 [Debug]: Load assets from xml with local ip&port is 192.168.197.33:5061
2020-06-01 05:06:31.326 [Debug]: 1 GB28181.App.SIPAccount assets loaded from XML record set.
2020-06-01 05:06:31.326 [Debug]: Starting file watch on /app/Config\gb28181.xml.
info: GB28181.Service.GBService[0]
      GB28181 Main Service is Running
info: GB28181.Service.GBService[0]
      GB28181 MainProc Worker running at: 06/01/2020 05:06:31 +00:00
2020-06-01 05:06:31.358 [Debug]: SIPMessageCore is runing at udp:192.168.197.33:5061
2020-06-01 05:06:31.367 [Debug]: SIPRegistrarCore is running at Udp:192.168.197.33:5061
2020-06-01 05:06:31.373 [Debug]: SIPUDPChannel socket on 0.0.0.0:5061 listening started.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at GB28181.Service.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in /src/GB28181.Server/Program.cs:line 48
```

**Comment by crazybber** [comment]
this is not a project code related issue ， 

1、check your aspnetcore development environment  and your configration  of ssh

2、check your error log ,which had also told you.
```csharp
Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
```
3、to ckeck project wiki may help you.
